Instance: CapabilityStatementEMPDClient
InstanceOf: CapabilityStatement
Usage: #definition
* url = "https://nhicore.nhi.gov.tw/empd/CapabilityStatement/CapabilityStatementEMPDClient"
* version = "0.1.0"
* name = "CapabilityStatementEMPDClient"
* title = "電子處方箋與調劑單張-用戶端"
* status = #active
* experimental = false
* date = "2023-11-20"
* description = "電子處方箋與調劑單張-用戶端(Client)之能力聲明"
* kind = #requirements
* fhirVersion = #4.0.1
* format[0] = #xml
* format[+] = #json
* patchFormat = #application/json-patch+json
* rest.mode = #client
* rest.documentation = "使用電子病歷交換-用戶端能力聲明中的查詢參數，支援讀取和查詢一個或多個Profile(s)。"
* rest.resource[0].type = #Bundle
* rest.resource[=].supportedProfile[0] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Bundle-EMPD"
* rest.resource[=].supportedProfile[+] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Bundle-DS"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[+].type = #Composition
* rest.resource[=].supportedProfile[0] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Composition-EMPD"
* rest.resource[=].supportedProfile[+] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Composition-DS"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[+].type = #Patient
* rest.resource[=].supportedProfile[0] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Patient-EMPD"
* rest.resource[=].supportedProfile[+] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Patient-DS"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[+].type = #Organization
* rest.resource[=].supportedProfile[0] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Organization-EMPD"
* rest.resource[=].supportedProfile[+] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Organization-DS"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[+].type = #Encounter
* rest.resource[=].supportedProfile[0] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Encounter-EMPD"
* rest.resource[=].supportedProfile[+] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Encounter-DS"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[+].type = #Condition
* rest.resource[=].supportedProfile[0] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Condition-EMPD"
* rest.resource[=].supportedProfile[+] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Condition-DS"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[+].type = #Observation
* rest.resource[=].supportedProfile[0] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Observation-EMPD-BodyWeight"
* rest.resource[=].supportedProfile[+] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Observation-DS-BodyWeight"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[+].type = #Media
* rest.resource[=].supportedProfile = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Media-DS"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[+].type = #Practitioner
* rest.resource[=].supportedProfile[0] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Practitioner-EMPD"
* rest.resource[=].supportedProfile[+] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Practitioner-DS"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[+].type = #Medication
* rest.resource[=].supportedProfile[0] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Medication-EMPD"
* rest.resource[=].supportedProfile[+] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Medication-DS"
* rest.resource[=].supportedProfile[+] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Medication-Self-EMPD"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[+].type = #MedicationRequest
* rest.resource[=].supportedProfile[0] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/MedicationRequest-EMPD"
* rest.resource[=].supportedProfile[+] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/MedicationRequest-DS"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[+].type = #Coverage
* rest.resource[=].supportedProfile = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Coverage-EMR"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[+].type = #ChargeItem
* rest.resource[=].supportedProfile = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/ChargeItem-DS"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[+].type = #MedicationDispense
* rest.resource[=].supportedProfile = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/MedicationDispense-DS"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves