Instance: CapabilityStatementEMPDServer
InstanceOf: CapabilityStatement
Usage: #definition
* url = "https://nhicore.nhi.gov.tw/empd/CapabilityStatement/CapabilityStatementEMPDServer"
* version = "0.1.0"
* name = "CapabilityStatementEMPDServer"
* title = "電子處方箋與調劑單張-伺服端"
* status = #active
* experimental = false
* date = "2023-11-20"
* description = "電子處方箋與調劑單張-伺服端(Server)之能力聲明"
* kind = #requirements
* fhirVersion = #4.0.1
* format[0] = #xml
* format[+] = #json
* patchFormat = #application/json-patch+json
* rest.mode = #server
* rest.documentation = "電子病歷交換-伺服端必須(SHALL)：(1)支援本實作指引中所有profiles (2)根據FHIR規範實作RESTful (3)回傳狀態碼-①(Status 400)：無效參數(invalid parameter)、②(Status 401/4xx)：未經授權的請求(unauthorized request)、③(Status 403)：未充分授權的資料存取範圍(insufficient premission scope)、④(Status 404)：未知的resource(unknown resource) (4)支援JSON格式 (5)可識別每個新增到Server的實例(instance)之meta.profile是否為電子病歷交換Profiles Defining URL，並確認實例是否依循profile製作。電子病歷交換-伺服端建議應該(SHOULD)：(1)支援XML格式。"
* rest.resource[0].type = #Bundle
* rest.resource[=].supportedProfile[0] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Bundle-EMPD"
* rest.resource[=].supportedProfile[+] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Bundle-DS"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[+].type = #Composition
* rest.resource[=].supportedProfile[0] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Composition-EMPD"
* rest.resource[=].supportedProfile[+] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Composition-DS"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[+].type = #Patient
* rest.resource[=].supportedProfile[0] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Patient-EMPD"
* rest.resource[=].supportedProfile[+] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Patient-DS"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[+].type = #Organization
* rest.resource[=].supportedProfile[0] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Organization-EMPD"
* rest.resource[=].supportedProfile[+] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Organization-DS"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[+].type = #Encounter
* rest.resource[=].supportedProfile[0] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Encounter-EMPD"
* rest.resource[=].supportedProfile[+] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Encounter-DS"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[+].type = #Condition
* rest.resource[=].supportedProfile[0] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Condition-EMPD"
* rest.resource[=].supportedProfile[+] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Condition-DS"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[+].type = #Observation
* rest.resource[=].supportedProfile[0] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Observation-EMPD-BodyWeight"
* rest.resource[=].supportedProfile[+] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Observation-DS-BodyWeight"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[+].type = #Media
* rest.resource[=].supportedProfile = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Media-DS"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[+].type = #Practitioner
* rest.resource[=].supportedProfile[0] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Practitioner-EMPD"
* rest.resource[=].supportedProfile[+] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Practitioner-DS"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[+].type = #Medication
* rest.resource[=].supportedProfile[0] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Medication-EMPD"
* rest.resource[=].supportedProfile[+] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Medication-DS"
* rest.resource[=].supportedProfile[+] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Medication-Self-EMPD"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[+].type = #MedicationRequest
* rest.resource[=].supportedProfile[0] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/MedicationRequest-EMPD"
* rest.resource[=].supportedProfile[+] = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/MedicationRequest-DS"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[+].type = #Coverage
* rest.resource[=].supportedProfile = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/Coverage-EMR"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[+].type = #ChargeItem
* rest.resource[=].supportedProfile = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/ChargeItem-DS"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves
* rest.resource[+].type = #MedicationDispense
* rest.resource[=].supportedProfile = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/MedicationDispense-DS"
* rest.resource[=].interaction[0].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #create
* rest.resource[=].interaction[+].extension.url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* rest.resource[=].interaction[=].extension.valueCode = #SHALL
* rest.resource[=].interaction[=].code = #update
* rest.resource[=].referencePolicy = #resolves