Logical: DSModel
Parent: Element
Id: ds-model
Title: "調劑單張-邏輯模型"
Description: "用於描述調劑單張邏輯模型"
* ^url = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/ds-model"
* ^version = "0.2.1"
* ^date = "2024-04-20"
* . ^short = "調劑單張邏輯模型"
* . ^definition = "用於描述調劑單張邏輯模型"
* ^type = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/DSModel"
* hospital 1..1 BackboneElement "醫療機構基本資料" "醫療機構基本資料"
* hospital.hospitalId 1..1 http://hl7.org/fhir/StructureDefinition/Identifier "醫療機構代碼" "醫療機構代碼"
* hospital.hospitalName 1..1 http://hl7.org/fhir/StructureDefinition/string "醫療機構名稱" "醫療機構名稱"
* hospital.hospitalTelecom 1..1 http://hl7.org/fhir/StructureDefinition/ContactPoint "醫療機構電話" "醫療機構電話"
* hospital.dispensingId 1..1 http://hl7.org/fhir/StructureDefinition/Identifier "調劑機構代碼" "調劑機構代碼"
* hospital.dispensingName 1..1 http://hl7.org/fhir/StructureDefinition/string "調劑機構名稱" "調劑機構名稱"
* hospital.dispensingAddress 1..1 http://hl7.org/fhir/StructureDefinition/string "調劑機構地址" "調劑機構地址"
* hospital.dispensingTelecom 1..1 http://hl7.org/fhir/StructureDefinition/ContactPoint "調劑機構電話" "調劑機構電話"
* patientInformation 1..1 BackboneElement "病患基本資料" "病患基本資料"
* patientInformation.personalIDNumber 1..1 http://hl7.org/fhir/StructureDefinition/Identifier "身分證號" "身分證號/護照號碼/居留證號"
* patientInformation.chartNo 0..1 http://hl7.org/fhir/StructureDefinition/Identifier "病歷號碼" "開立處方箋機構之病人病歷號碼"
* patientInformation.name 1..1 http://hl7.org/fhir/StructureDefinition/string "姓名" "姓名"
* patientInformation.gender 1..1 http://hl7.org/fhir/StructureDefinition/code "性別" "性別"
* patientInformation.birthDate 1..1 http://hl7.org/fhir/StructureDefinition/date "出生日期" "出生日期。格式為西元YYYYMMDD"
* patientInformation.age 1..1 http://hl7.org/fhir/StructureDefinition/Age "就診年齡" "就診年齡"
* patientInformation.identityType 1..1 http://hl7.org/fhir/StructureDefinition/BackboneElement "就醫身分別" "就醫身分別。健保/非健保"
* patientInformation.bodyWeight 0..1 http://hl7.org/fhir/StructureDefinition/Quantity "體重" "體重。若調劑藥物劑量須配合體重而有所調整，此欄位為必填"
* outpatientInformation 1..1 BackboneElement "門診基本資料" "門診基本資料"
* outpatientInformation.opdDate 1..1 http://hl7.org/fhir/StructureDefinition/date "門診日期" "門診日期。等同開立處方日期，格式為西元YYYMMDD"
* outpatientInformation.department 1..1 http://hl7.org/fhir/StructureDefinition/string "科別" "科別"
* outpatientInformation.originalIdentifier 0..1 http://hl7.org/fhir/StructureDefinition/Identifier "原就醫識別碼" "原就醫識別碼。醫療院所開立處方時之就醫識別碼"
* outpatientInformation.identifier 0..1 http://hl7.org/fhir/StructureDefinition/Identifier "就醫識別碼" "就醫識別碼。本次調劑處方所產製之就醫識別碼"
* outpatientInformation.note 1..1 http://hl7.org/fhir/StructureDefinition/Annotation "部分負擔代碼" "部分負擔代碼"
* outpatientInformation.medicaltreatmentNumber 0..1 http://hl7.org/fhir/StructureDefinition/Identifier "健保卡就醫序號" "健保卡就醫序號"
* outpatientInformation.class 0..1 http://hl7.org/fhir/StructureDefinition/Coding "案件分類" "案件分類"
* outpatientInformation.type 0..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "給付類別" "給付類別"
* outpatientInformation.pharmacyServiceCode 0..1 http://hl7.org/fhir/StructureDefinition/Coding "藥事服務代碼" "藥事服務代碼"
* outpatientInformation.authorizationCode 0..1 http://hl7.org/fhir/StructureDefinition/Identifier "處方箋存取授權碼" "處方箋存取授權碼"
* outpatientInformation.belong 0..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "歸屬" "歸屬。建議為計畫案之開立處方，如：藥事照護計畫、戒菸門診、COVID-19…等特殊案件代碼"
* practitionerInformation 1..1 BackboneElement "醫事人員基本資料" "醫事人員基本資料"
* practitionerInformation.physicianName 1..1 http://hl7.org/fhir/StructureDefinition/HumanName "醫師姓名" "醫師姓名"
* practitionerInformation.licenseNumber 0..1 http://hl7.org/fhir/StructureDefinition/Identifier "管制藥品使用執照號碼" "管制藥品使用執照號碼。開立第一級、第二級及第三級管制藥品專用處方箋，此欄位為必填"
* practitionerInformation.physicianTelecom 0..1 http://hl7.org/fhir/StructureDefinition/ContactPoint "醫師聯絡電話" "醫師聯絡電話。開立第一級、第二級及第三級管制藥品專用處方箋，此欄位為必填"
* practitionerInformation.professionalCertificate 0..1 http://hl7.org/fhir/StructureDefinition/Identifier "調劑人員專業證書字號" "調劑人員專業證書字號。開立第一級、第二級及第三級管制藥品專用處方箋，此欄位為必填。\r\n此欄位等同藥師證書字號"
* practitionerInformation.pharmacyPersonnelName 1..1 http://hl7.org/fhir/StructureDefinition/HumanName "藥事人員姓名" "藥事人員姓名。註：此為調製藥事人員姓名"
* diagnosis 1..* BackboneElement "診斷" "診斷"
* diagnosis.code 1..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "國際疾病分類代碼 ICD Code(International Classification of Diseases)" "國際疾病分類代碼 ICD Code(International Classification of Diseases)。應含主診斷或次診斷之ICD代碼"
* diagnosis.note 0..1 http://hl7.org/fhir/StructureDefinition/Annotation "醫療評估內容註記" "醫療評估內容註記"
* typeOfPrescriptionNo 1..1 http://hl7.org/fhir/StructureDefinition/Identifier "處方箋單號" "處方箋單號"
* typesofPrescription 1..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "處方箋種類註記" "處方箋種類註記。\r\n填寫代碼如下\r\nA：一般處方箋：處方用藥，一次給予7日(含)以下之用藥量\r\nB：慢性病處方箋\r\nC：慢性病連續處方箋\r\nD：管制藥品專用處方箋(一般)\r\nE：管制藥品專用處方箋(慢箋)\r\nF：管制藥品專用處方箋（慢連箋）"
* typeOfPrescriptionNote 1..1 http://hl7.org/fhir/StructureDefinition/Annotation "須被合併之處方箋註記" "須被合併之處方箋註記。合併請填是，預設值為「否」。說明：同時開立管制藥品及一般藥品時，須開立二張處方箋，並在這二張處方箋此欄位上註記「是」"
* typeOfPrescriptionDate 1..1 BackboneElement "處方箋有效日期" "處方箋有效日期"
* typeOfPrescriptionDate.date 1..1 http://hl7.org/fhir/StructureDefinition/date "處方箋有效日期" "處方箋有效日期。包含第二次之後的建議領藥日期；格式為西元YYYYMMDD"
* typeOfPrescriptionDate.note 0..1 http://hl7.org/fhir/StructureDefinition/Annotation "處方箋註銷註記" "處方箋註銷註記。註銷請填Y，並至處方箋有效日期更新為處方箋註銷日期\r\n說明：用於就醫當次未調劑處方或第2次(含)以後未調劑慢連箋處方之註銷"
* totalMedicationDays 1..1 http://hl7.org/fhir/StructureDefinition/positiveInt "給藥總日份" "給藥總日份"
* refillTimes 1..1 http://hl7.org/fhir/StructureDefinition/unsignedInt "連續處方可調劑次數" "連續處方可調劑次數"
* dispensingIdentifier 0..1 http://hl7.org/fhir/StructureDefinition/Identifier "連續處方箋調劑序號" "連續處方箋調劑序號"
* dispensingContent 1..* BackboneElement "調劑內容" "調劑內容"
* dispensingContent.category 0..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "醫令類別" "醫令類別"
* dispensingContent.item 1..1 http://hl7.org/fhir/StructureDefinition/Identifier "項次" "項次"
* dispensingContent.healthInsuranceCode 0..1 http://hl7.org/fhir/StructureDefinition/code "健保代碼" "健保代碼"
* dispensingContent.brandName 1..1 http://hl7.org/fhir/StructureDefinition/string "藥品商品名稱" "藥品商品名稱。註：此為用於調製之藥品名稱"
* dispensingContent.genericName 1..1 http://hl7.org/fhir/StructureDefinition/string "學名" "學名"
* dispensingContent.batchNumber 0..* http://hl7.org/fhir/StructureDefinition/Identifier "藥品批號" "藥品批號"
* dispensingContent.reason 0..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "不得以其他廠牌藥品替代之理由" "不得以其他廠牌藥品替代之理由。填寫說明：有特殊情況時才填寫"
* dispensingContent.drugUnitContent 1..1 http://hl7.org/fhir/StructureDefinition/Ratio "藥品單位含量" "藥品單位含量"
* dispensingContent.dosageForm 1..1 http://hl7.org/fhir/StructureDefinition/string "劑型" "劑型。如藥丸、藥水等"
* dispensingContent.dose 1..1 http://hl7.org/fhir/StructureDefinition/decimal "劑量" "劑量"
* dispensingContent.doseUnits 1..1 http://hl7.org/fhir/StructureDefinition/string "劑量單位" "劑量單位。如：顆、CC等"
* dispensingContent.frequency 1..1 http://hl7.org/fhir/StructureDefinition/positiveInt "頻率" "頻率"
* dispensingContent.usageTime 0..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "使用時間" "使用時間。如：飯前後"
* dispensingContent.routeOfAdministration 1..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "給藥途徑" "給藥途徑"
* dispensingContent.medicationDays 1..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "給藥日數" "給藥日數"
* dispensingContent.totalAmount 1..1 http://hl7.org/fhir/StructureDefinition/decimal "給藥總量" "給藥總量"
* dispensingContent.totalUnits 1..1 http://hl7.org/fhir/StructureDefinition/string "給藥總量單位" "給藥總量單位。如：顆、CC、瓶等"
* dispensingContent.radiopharmaceuticalName 0..1 http://hl7.org/fhir/StructureDefinition/Annotation "調劑之核種名稱" "調劑之核種名稱。僅調劑核醫放射性藥品須填寫"
* dispensingContent.radiopharmaceuticalActivity 0..1 http://hl7.org/fhir/StructureDefinition/Annotation "調劑之放射活度" "調劑之放射活度。僅調劑核醫放射性藥品須填寫"
* dispensingContent.completedRadiopharmaceuticalActivity 0..1 http://hl7.org/fhir/StructureDefinition/Annotation "完成調劑之放射活度" "完成調劑之放射活度。僅調劑核醫放射性藥品須填寫"
* dispensingContent.completedQuantityOfNuclearMedicineRadiopharmaceuticals 0..1 http://hl7.org/fhir/StructureDefinition/Annotation "完成調劑之核醫放射性藥品數量" "完成調劑之核醫放射性藥品數量。僅調劑核醫放射性藥品須填寫"
* dispensingContent.substitutedNote 1..1 http://hl7.org/fhir/StructureDefinition/boolean "有更換藥品註記" "有更換藥品註記。預設為「無」\r\n填寫說明：\r\n有更換藥品時請填寫「有」\r\n無有更換藥品請填寫「無」"
* dispensingContent.typeOfPrescriptionAmbiguityPatternFlag 1..1 http://hl7.org/fhir/StructureDefinition/Annotation "處方疑義樣態註記" "處方疑義樣態註記。預設為「無」\r\n填寫說明：\r\n處方有疑義樣態時請填寫「有」\r\n處方無疑義樣態請填寫「無」"
* dispensingContent.selfPayNote 0..1 http://hl7.org/fhir/StructureDefinition/Annotation "自費註記" "自費註記。自費標註為“Y”，健保給付標註為“N”"
* dispensingContent.typeOfPrescriptionDispensingMethod 1..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "醫令調劑方式" "醫令調劑方式"
* dispensingContent.dosageInstruction 0..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "用藥指示" "用藥指示"
* dispensingTime 1..1 http://hl7.org/fhir/StructureDefinition/date "調劑時間" "調劑時間"
* pickTime 1..1 http://hl7.org/fhir/StructureDefinition/date "取藥時間" "取藥時間"
* recipientInformation 0..1 BackboneElement "領藥者基本資料" "領藥者基本資料"
* recipientInformation.relationship 0..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "與用藥對象之關係" "與用藥對象之關係。開立第一級、第二級及第三級管制藥品專用處方箋，此欄位為必填\r\n參考項目：本人、家屬、朋友、看護、志工、其他"
* recipientInformation.name 0..1 http://hl7.org/fhir/StructureDefinition/HumanName "領藥者姓名" "領藥者姓名。開立第一級、第二級及第三級管制藥品專用處方箋，此欄位為必填"
* recipientInformation.telecom 0..1 http://hl7.org/fhir/StructureDefinition/ContactPoint "領藥者連絡電話" "領藥者連絡電話。開立第一級、第二級及第三級管制藥品專用處方箋，此欄位為必填"
* recipientInformation.electronicSignature 0..1 http://hl7.org/fhir/StructureDefinition/Attachment "領藥者電子簽章" "領藥者電子簽章"

Mapping: DS
Id: DS
Title: "DSModel"
Source: DSModel
Target: "https://nhicore.nhi.gov.tw/empd"
* hospital.hospitalId -> "醫療機構代碼:Organization.identifier.value"
* hospital.hospitalName -> "醫療機構名稱:Organization.name"
* hospital.hospitalTelecom -> "醫療機構電話:Organization.telecom.value"
* hospital.dispensingId -> "調劑機構代碼:Organization.identifier.value"
* hospital.dispensingName -> "調劑機構名稱:Organization.name"
* hospital.dispensingAddress -> "調劑機構地址:Organization.address.text"
* hospital.dispensingTelecom -> "調劑機構電話:Organization.telecom.value"
* patientInformation.personalIDNumber -> "身分證號:Patient.identifier"
* patientInformation.chartNo -> "病歷號碼:Patient.identifier"
* patientInformation.name -> "姓名:Patient.name"
* patientInformation.gender -> "性別:Patient.gender"
* patientInformation.birthDate -> "出生日期:birthDate"
* patientInformation.age -> "就診年齡:Patient.extension"
* outpatientInformation.opdDate -> "門診日期:Encounter.period.star"
* outpatientInformation.department -> "科別:Encounter.serviceType"
* outpatientInformation.originalIdentifier -> "原就醫識別碼:Encounter.identifier.value"
* outpatientInformation.identifier -> "就醫識別碼:Encounter.identifier.value"
* outpatientInformation.note -> "部分負擔代碼:Condition.note"
* outpatientInformation.medicaltreatmentNumber -> "健保卡就醫序號:Encounter.identifier.value"
* outpatientInformation.class -> "案件分類:Encounter.class"
* outpatientInformation.type -> "給付類別:Coverage.type"
* outpatientInformation.pharmacyServiceCode -> "藥事服務代碼:ChargeItem.code"
* outpatientInformation.authorizationCode -> "處方箋存取授權碼:MedicationRequest.identifier"
* outpatientInformation.belong -> "歸屬:Encounter.type"
* practitionerInformation.physicianName -> "醫師姓名:Practitioner.name"
* practitionerInformation.licenseNumber -> "管制藥品使用執照號碼:Practitioner.identifier.value"
* practitionerInformation.physicianTelecom -> "醫師聯絡電話:Practitioner.telecom.value"
* practitionerInformation.professionalCertificate -> "調劑人員專業證書字號:Practitioner.qualification.identifier.value"
* practitionerInformation.pharmacyPersonnelName -> "藥事人員姓名:Practitioner.name"
* diagnosis.code -> "國際疾病分類代碼 ICD Code(International Classification of Diseases):Condition.code"
* diagnosis.note -> "醫療評估內容註記:Condition.note"
* typeOfPrescriptionNo -> "處方箋單號:MedicationRequest.identifier"
* typesofPrescription -> "處方箋種類註記:MedicationRequest.category"
* typeOfPrescriptionNote -> "須被合併之處方箋註記:MedicationRequest.note"
* typeOfPrescriptionDate.date -> "處方箋有效日期:MedicationRequest.dispenseRequest.validityPeriod.end"
* typeOfPrescriptionDate.note -> "處方箋註銷註記:MedicationRequest.note"
* totalMedicationDays -> "給藥總日份:MedicationRequest.extension"
* refillTimes -> "連續處方可調劑次數:MedicationRequest.dispenseRequest.numberOfRepeatsAllowed"
* dispensingIdentifier -> "連續處方箋調劑序號:MedicationRequest.identifier.value"
* dispensingContent.category -> "醫令類別:MedicationDispense.category"
* dispensingContent.item -> "項次:MedicationDispense.identifier"
* dispensingContent.healthInsuranceCode -> "健保代碼:Medication.code"
* dispensingContent.healthInsuranceCode -> "健保代碼:MedicationDispense.medication[x]:medicationCodeableConcept"
* dispensingContent.brandName -> "藥品商品名稱:MedicationDispense.medication[x]:medicationCodeableConcept"
* dispensingContent.brandName -> "藥品商品名稱:Medication.code"
* dispensingContent.genericName -> "學名:MedicationDispense.medication[x]:medicationCodeableConcept.text"
* dispensingContent.genericName -> "學名:Medication.code"
* dispensingContent.batchNumber -> "藥品批號:Medication.identifier"
* dispensingContent.batchNumber -> "藥品批號:MedicationDispense.identifier"
* dispensingContent.reason -> "不得以其他廠牌藥品替代之理由:MedicationDispense.substitution.reason"
* dispensingContent.drugUnitContent -> "藥品單位含量:Medication.ingredient.strength"
* dispensingContent.dosageForm -> "劑型:Medication.form"
* dispensingContent.dose -> "劑量:MedicationDispense.dosageInstruction.doseAndRate.doseQuantity.value"
* dispensingContent.doseUnits -> "劑量單位:MedicationDispense.dosageInstruction.doseAndRate.doseQuantity.unit"
* dispensingContent.frequency -> "頻率:MedicationDispense.dosageInstruction.timing.repeat.frequency"
* dispensingContent.usageTime -> "使用時間:MedicationDispense.dosageInstruction.timing.code"
* dispensingContent.routeOfAdministration -> "給藥途徑:MedicationDispense.dosageInstruction.route"
* dispensingContent.medicationDays -> "給藥日數:MedicationDispense.daysSupply"
* dispensingContent.totalAmount -> "給藥總量:MedicationDispense.quantity.value"
* dispensingContent.totalUnits -> "給藥總量單位:MedicationDispense.quantity.unit"
* dispensingContent.radiopharmaceuticalName -> "調劑之核種名稱:MedicationDispense.note"
* dispensingContent.radiopharmaceuticalActivity -> "調劑之放射活度:MedicationDispense.note"
* dispensingContent.completedRadiopharmaceuticalActivity -> "完成調劑之放射活度:MedicationDispense.note"
* dispensingContent.completedQuantityOfNuclearMedicineRadiopharmaceuticals -> "完成調劑之核醫放射性藥品數量:MedicationDispense.note"
* dispensingContent.substitutedNote -> "有更換藥品註記:MedicationDispense.substitution.wasSubstituted"
* dispensingContent.typeOfPrescriptionAmbiguityPatternFlag -> "處方疑義樣態註記:MedicationDispense.note"
* dispensingContent.selfPayNote -> "自費註記:MedicationRequest.note"
* dispensingContent.typeOfPrescriptionDispensingMethod -> "醫令調劑方式:MedicationRequest.category"
* dispensingContent.dosageInstruction -> "用藥指示:MedicationRequest.dosageInstruction.method"
* dispensingTime -> "調劑時間:MedicationRequest.dispenseRequest.validityPeriod.start"
* pickTime -> "取藥時間:MedicationRequest.authoredOn"
* recipientInformation.relationship -> "與用藥對象之關係:Patient.contact.relationship"
* recipientInformation.name -> "領藥者姓名:Patient.contact.name"
* recipientInformation.telecom -> "領藥者連絡電話:Patient.contact.telecom"
* recipientInformation.electronicSignature -> "領藥者電子簽章:Media.content"