Logical: EMPDModel
Parent: Element
Id: ep-model
Title: "電子處方箋-邏輯模型"
Description: "用於描述電子處方箋邏輯模型"
* ^url = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/ep-model"
* ^version = "0.2.1"
* ^date = "2024-04-20"
* . ^short = "電子處方箋邏輯模型"
* . ^definition = "用於描述電子處方箋邏輯模型"
* ^type = "https://nhicore.nhi.gov.tw/empd/StructureDefinition/EMPDModel"
* hospital 1..1 BackboneElement "醫事機構基本資料" "醫事機構基本資料"
* hospital.hospitalId 1..1 http://hl7.org/fhir/StructureDefinition/Identifier "醫療機構代碼" "醫療機構代碼"
* hospital.hospitalName 1..1 http://hl7.org/fhir/StructureDefinition/string "醫療機構名稱" "醫療機構名稱"
* hospital.address 1..1 http://hl7.org/fhir/StructureDefinition/Address "醫療機構地址" "醫療機構地址"
* hospital.telecom 1..1 http://hl7.org/fhir/StructureDefinition/ContactPoint "醫療機構電話" "醫療機構電話"
* patientInformation 1..1 BackboneElement "病人基本資料" "病人基本資料"
* patientInformation.idNumber 1..1 http://hl7.org/fhir/StructureDefinition/Identifier "身分證號" "身分證號/護照號碼/居留證號"
* patientInformation.chartNo 0..1 http://hl7.org/fhir/StructureDefinition/Identifier "病歷號碼" "病歷號碼"
* patientInformation.name 1..1 http://hl7.org/fhir/StructureDefinition/HumanName "姓名" "姓名"
* patientInformation.gender 1..1 http://hl7.org/fhir/StructureDefinition/code "性別" "性別"
* patientInformation.birthDate 1..1 http://hl7.org/fhir/StructureDefinition/date "出生日期" "出生日期，格式為西元YYYYMMDD"
* patientInformation.age 1..1 http://hl7.org/fhir/StructureDefinition/Age "就診年齡" "就診年齡"
* patientInformation.identityType 1..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "就醫身分別" "就醫身分別，健保、非健保"
* patientInformation.weight 0..1 http://hl7.org/fhir/StructureDefinition/Quantity "體重" "體重。若調劑藥物劑量須配合體重而有所調整，此欄位為必填"
* outpatient 1..1 BackboneElement "門診基本資料" "門診基本資料"
* outpatient.opdDate 1..1 http://hl7.org/fhir/StructureDefinition/dateTime "門診日期" "門診日期，等同開立處方日期，格式為西元YYYYMMDD"
* outpatient.department 1..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "科別" "科別"
* outpatient.medicalIdentifier 1..1 http://hl7.org/fhir/StructureDefinition/Identifier "就醫識別碼" "就醫識別碼"
* outpatient.note 0..1 http://hl7.org/fhir/StructureDefinition/Annotation "部分負擔代碼" "部分負擔代碼"
* outpatient.medicaltreatmentNumber 0..1 http://hl7.org/fhir/StructureDefinition/Identifier "健保卡就醫序號" "健保卡就醫序號"
* outpatient.class 0..1 http://hl7.org/fhir/StructureDefinition/Coding "案件分類" "案件分類。\r\n健保案件分類，如01:西醫一般案件 02:西醫急診 03:西醫門診手術 04:西醫慢性病 05:洗腎 06:結核病 08:慢性病連續處方調劑 09:西醫其他專案 11:牙醫一般案件 12:牙醫急診 13:牙醫門診手術等。\r\n自費案件可免填。"
* outpatient.type 0..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "給付類別" "給付類別。此欄位涉及藥局向民眾收取部分負擔金額判斷，且藥局申報給付類別需依照原處方所列給付類別代碼申報。\r\n依健保卡上傳資料格式 2.0 填寫(非必填)\r\n1:職業傷害\r\n2:職業病\r\n3:普通傷害\r\n4:普通疾病\r\n8:天然災害\r\n9:呼吸照護\r\nD:起雲劑\r\nY:八仙樂園粉塵暴燃事件\r\nZ:高雄市氣爆事件"
* practitionerInformation 1..1 BackboneElement "醫事人員基本資料" "醫事人員基本資料"
* practitionerInformation.physicianName 1..1 http://hl7.org/fhir/StructureDefinition/HumanName "醫師姓名" "醫師姓名"
* practitionerInformation.licenseNumber 0..1 http://hl7.org/fhir/StructureDefinition/Identifier "管制藥品使用執照號碼" "管制藥品使用執照號碼。開立第一級、第二級及第三級管制藥品專用處方箋，此欄位為必填。"
* practitionerInformation.telecom 0..1 http://hl7.org/fhir/StructureDefinition/ContactPoint "醫師聯絡電話" "醫師聯絡電話。開立第一級、第二級及第三級管制藥品專用處方箋，此欄位為必填。"
* practitionerInformation.certificateNo 0..1 http://hl7.org/fhir/StructureDefinition/Identifier "醫事人員證書字號" "醫事人員證書字號"
* diagnose 1..* BackboneElement "診斷" "診斷"
* diagnose.icdCode 1..1 http://hl7.org/fhir/StructureDefinition/code "國際疾病分類代碼ICD Code(International Classification of Diseases)" "國際疾病分類代碼ICD Code(International Classification of Diseases)，應含主診斷或次診斷之ICD代碼"
* diagnose.note 0..1 http://hl7.org/fhir/StructureDefinition/Annotation "醫療評估內容註記" "醫療評估之內容註記"
* prescriptionNo 1..1 http://hl7.org/fhir/StructureDefinition/Identifier "處方箋單號" "處方箋單號"
* typeofPrescription 1..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "處方箋種類註記" "處方箋種類註記\r\nA:一般處方箋:處方用藥，一次給予7日(含)以下之用藥量\r\nB:慢性病處方箋\r\nC:慢性病連續處方箋\r\nD:管制藥品專用處方箋(一般)\r\nE:管制藥品專用處方箋(慢箋)\r\nF管制藥品專用處方箋(慢連箋)"
* combinedPrescriptionNote 1..1 http://hl7.org/fhir/StructureDefinition/Annotation "須被合併之處方箋註記" "須被合併之處方箋註記。\r\n合併請填是，預設值為「否」。說明：同時開立管制藥品及一般藥品時，須開立二張處方箋，並在這二張處方箋此欄位上註記「是」。"
* prescriptionDatetime 1..1 BackboneElement "處方箋有效日期" "處方箋有效日期"
* prescriptionDatetime.datetime 1..* http://hl7.org/fhir/StructureDefinition/dateTime "處方箋有效日期" "處方箋有效日期，包含第二次之後的建議領藥日期；格式為西元YYYYMMDD"
* prescriptionDatetime.note 0..1 http://hl7.org/fhir/StructureDefinition/Annotation "處方箋註銷註記" "處方箋註銷註記，註銷請填Y，並至處方箋有效日期更新為處方箋註銷日期說明：\r\n用於就醫當次未調劑處方或第二次(含)以後未調劑慢連箋處方之註銷"
* totalMedicationsDays 1..1 http://hl7.org/fhir/StructureDefinition/positiveInt "給藥總日份" "給藥總日份"
* refillTimes 1..1 http://hl7.org/fhir/StructureDefinition/unsignedInt "連續處方可調劑次數" "連續處方可調劑次數"
* prescriptionContent 1..* BackboneElement "處方內容" "處方內容"
* prescriptionContent.orderType 1..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "醫令類別" "藉由「醫令類別」區分是否為藥品或特殊材料。"
* prescriptionContent.item 1..1 http://hl7.org/fhir/StructureDefinition/Identifier "項次" "項次。使民眾及藥局確認藥品品項數。"
* prescriptionContent.code 1..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "健保代碼" "健保代碼"
* prescriptionContent.brandName 0..1 http://hl7.org/fhir/StructureDefinition/string "藥品商品名稱" "藥品商品名稱"
* prescriptionContent.genericName 1..1 http://hl7.org/fhir/StructureDefinition/string "學名" "學名"
* prescriptionContent.substitution 0..1 http://hl7.org/fhir/StructureDefinition/BackboneElement "不得以其他廠牌藥品替代之理由" "不得以其他廠牌藥品替代之理由。填寫說明：有特殊情況時才填寫。"
* prescriptionContent.drugunitContent 1..1 http://hl7.org/fhir/StructureDefinition/Ratio "藥品單位含量" "藥品單位含量"
* prescriptionContent.dosageForm 1..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "劑型" "劑型，如藥水、藥丸等"
* prescriptionContent.dose 1..1 http://hl7.org/fhir/StructureDefinition/decimal "劑量" "劑量"
* prescriptionContent.doseUnits 0..* http://hl7.org/fhir/StructureDefinition/string "劑量單位" "劑量單位，如：顆、CC等"
* prescriptionContent.frequency 1..1 http://hl7.org/fhir/StructureDefinition/positiveInt "頻率" "頻率"
* prescriptionContent.usagetime 0..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "使用時間" "使用時間，如飯前後"
* prescriptionContent.routeofAdministration 1..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "給藥途徑" "給藥途徑"
* prescriptionContent.medicationDays 1..1 http://hl7.org/fhir/StructureDefinition/Duration "給藥日數" "給藥日數"
* prescriptionContent.totalAmount 1..1 http://hl7.org/fhir/StructureDefinition/decimal "給藥總量" "給藥總量"
* prescriptionContent.totalUnits 1..1 http://hl7.org/fhir/StructureDefinition/string "給藥總量單位" "給藥總量單位，如：顆、CC、瓶等"
* prescriptionContent.selfnote 0..1 http://hl7.org/fhir/StructureDefinition/Annotation "自費註記" "自費註記"
* prescriptionContent.directions 0..1 http://hl7.org/fhir/StructureDefinition/CodeableConcept "用藥指示" "用藥指示"

Mapping: EMPD
Id: EMPD
Title: "EMPDModel"
Source: EMPDModel
Target: "https://nhicore.nhi.gov.tw/empd"
* hospital.hospitalId -> "醫療機構代碼:Organization.Identifier"
* hospital.hospitalName -> "醫療機構名稱:Organization.name"
* hospital.address -> "醫療機構地址:Organization.address"
* hospital.telecom -> "醫療機構電話:Organization.telecom"
* patientInformation.idNumber -> "身分證號:Patient.identifier"
* patientInformation.chartNo -> "病歷號碼:Patient.identifier"
* patientInformation.name -> "姓名:Patient.name"
* patientInformation.gender -> "性別:Patient.gender"
* patientInformation.birthDate -> "出生日期:Patient.birthDate"
* patientInformation.age -> "就診年齡:Patient.extension.valueAge"
* patientInformation.identityType -> "就醫身分別:Coverage"
* patientInformation.weight -> "體重:Observation.valueQuantity"
* outpatient.opdDate -> "門診日期:Encounter.period.start"
* outpatient.department -> "科別:Encounter.serviceType"
* outpatient.medicalIdentifier -> "就醫識別碼:Encounter.identifier"
* outpatient.note -> "部分負擔代碼:Condition.note"
* outpatient.medicaltreatmentNumber -> "健保卡就醫序號:Encounter.identifier"
* outpatient.class -> "案件分類:Encounter.class"
* outpatient.type -> "給付類別:Coverage.type"
* practitionerInformation.physicianName -> "醫師姓名:Practitioner.name"
* practitionerInformation.licenseNumber -> "管制藥品使用執照號碼:Practitioner.identifier.value"
* practitionerInformation.telecom -> "醫師聯絡電話:Practitioner.telecom.value"
* practitionerInformation.certificateNo -> "醫事人員證書字號:Practitioner.qualification.identifier.value"
* diagnose.icdCode -> "國際疾病分類代碼:Condition.code.coding.code"
* diagnose.note -> "醫療評估之內容註記:Condition.note"
* prescriptionNo -> "處方箋單號:MedicationRequest.identifier"
* typeofPrescription -> "處方箋種類註記:MedicationRequest.category"
* combinedPrescriptionNote -> "須被合併之處方箋註記:MedicationRequest.note"
* prescriptionDatetime.datetime -> "處方箋有效日期:Composition.date"
* prescriptionDatetime.note -> "處方箋註銷註記:MedicationRequest.note"
* totalMedicationsDays -> "給藥總日份:MedicationRequest.extension"
* refillTimes -> "連續處方可調劑次數:MedicationRequest.dispenseRequest.numberOfRepeatsAllowed"
* prescriptionContent.orderType -> "醫令類別:MedicationRequest.category"
* prescriptionContent.item -> "項次:MedicationRequest.identifier"
* prescriptionContent.code -> "健保代碼:Medication.code"
* prescriptionContent.brandName -> "藥品商品名稱Medication.code.coding.display，使用學名則填入於Medication.code.text"
* prescriptionContent.genericName -> "學名:Medication.code.text或Medication.code.coding.display"
* prescriptionContent.substitution -> "不得以其他廠牌藥品替代之理由:MedicationRequest.substitution"
* prescriptionContent.drugunitContent -> "藥品單位含量:Medication.ingredient.strength"
* prescriptionContent.dosageForm -> "劑型:Medication.form"
* prescriptionContent.dose -> "劑量:MedicationRequest.dosageInstruction.doseAndRate.doseQuantity.value"
* prescriptionContent.doseUnits -> "劑量單位:MedicationRequest.dosageInstruction.doseAndRate.doseQuantity.unit"
* prescriptionContent.frequency -> "頻率:MedicationRequest.dosageInstruction.timing.repeat.frequency"
* prescriptionContent.usagetime -> "使用時間:MedicationRequest.dosageInstruction.timing.code"
* prescriptionContent.routeofAdministration -> "給藥途徑:MedicationRequest.dosageInstruction.route"
* prescriptionContent.medicationDays -> "給藥日數:MedicationRequest.dispenseRequest.expectedSupplyDuration"
* prescriptionContent.totalAmount -> "給藥總量:MedicationRequest.dispenseRequest.quantity.value"
* prescriptionContent.totalUnits -> "給藥總量單位:MedicationRequest.dispenseRequest.quantity.unit"
* prescriptionContent.selfnote -> "自費註記:MedicationRequest.note"
* prescriptionContent.directions -> "用藥指示:MedicationRequest.dosageInstruction.method"